// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL1TbqT6gL2S8okbH-nhk8RqZag9UInjY',
    appId: '1:701590346336:android:4550e80b7a8cf67183c105',
    messagingSenderId: '701590346336',
    projectId: 'schoolmanagement-3030e',
    storageBucket: 'schoolmanagement-3030e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR46FDXCu18Wzrq8ekwPvAPeQEpUNsCSQ',
    appId: '1:701590346336:web:9b9377f596660e5683c105',
    messagingSenderId: '701590346336',
    projectId: 'schoolmanagement-3030e',
    authDomain: 'schoolmanagement-3030e.firebaseapp.com',
    storageBucket: 'schoolmanagement-3030e.firebasestorage.app',
    measurementId: 'G-66DVSMWZJ0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrf8pDxOG7G6XxaueIcXNjUDkVv-gxn6M',
    appId: '1:701590346336:ios:f4d402a3d59483c383c105',
    messagingSenderId: '701590346336',
    projectId: 'schoolmanagement-3030e',
    storageBucket: 'schoolmanagement-3030e.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR46FDXCu18Wzrq8ekwPvAPeQEpUNsCSQ',
    appId: '1:701590346336:web:8cba65414cd9f4a783c105',
    messagingSenderId: '701590346336',
    projectId: 'schoolmanagement-3030e',
    authDomain: 'schoolmanagement-3030e.firebaseapp.com',
    storageBucket: 'schoolmanagement-3030e.firebasestorage.app',
    measurementId: 'G-MM5G3BR7QG',
  );

}